server:
  port: 8089

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      discovery:
        locator:
          enabled: true
      routes:
        - id: article-service
          uri: lb://article-service
          predicates:
            - Path=/article/**
          filters:
            - RewritePath=/article/(?<path>.*), /$\{path}

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment/**
          filters:
            - RewritePath=/comment/(?<path>.*), /$\{path}

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/review/**
          filters:
            - RewritePath=/review/(?<path>.*), /$\{path}

        - id: notification-websocket
          uri: lb:ws://notification-service
          predicates:
            - Path=/notification-ws/**
          filters:
            - RemoveRequestHeader=Sec-WebSocket-Protocol
            - RemoveRequestHeader=Sec-WebSocket-Extensions
            - StripPrefix=1

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - RewritePath=/notification/(?<path>.*), /$\{path}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Upgrade"
              - "Connection"
              - "Sec-WebSocket-Accept"
              - "Sec-WebSocket-Key"
              - "Sec-WebSocket-Version"
            allowCredentials: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
