name: SpringCloud
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cloudservice-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  db_articleservice:
    container_name: db_articleservice
    image: mariadb:latest
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: db_articleservice
    networks:
      - cloudservice-network
    volumes:
      - db_articleservice_data:/var/lib/mysql

  db_reviewservice:
    container_name: db_reviewservice
    image: mariadb:latest
    ports:
      - "3326:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: db_reviewservice
    networks:
      - cloudservice-network
    volumes:
      - db_reviewservice_data:/var/lib/mysql

  db_commentservice:
    container_name: db_commentservice
    image: mariadb:latest
    ports:
      - "3336:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: db_commentservice
    networks:
      - cloudservice-network
    volumes:
      - db_commentservice_data:/var/lib/mysql

volumes:
  rabbitmq_data:
  db_articleservice_data:
  db_reviewservice_data:
  db_commentservice_data:

networks:
  cloudservice-network:
    driver: bridge