name: JavaFullstackBackend
services:
  postservice_db:
    container_name: postservice_db
    image: mariadb:latest
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: postservice_db
  nextservice_db:
    container_name: nextservice_db
    image: mariadb:latest
    ports:
      - "3326:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: nextservice_db
